apiVersion: v1
kind: Service
metadata:
        name: clusterip-pod
spec:
        type: ClusterIP
        selector:
                app: nginx-pod
        ports:
                - protocol: TCP
                  port: 80
                  targetPort: 80
