apiVersion: v1
kind: Service
metadata:
  name: loadbalancer-deployment
spec:
  type: LoadBalancer
  externalIPs:
          # - 10.178.0.8
 # - 10.178.0.9
  selector:
    app: nginx-deploy
  ports:
  - protocol: TCP
    port: 80
